### ISSUE TITLE
Workflow para publicar SweetTicketDesign en Maven Repository

### ISSUE THREAD

**Issue by velnae** [puyu-pe/SweetTicketDesign#2]
- Comunicarse con Soporte de Nexus repository de maven.
- Crear un lista de pasos a realizar para la migración
- Coordinar la fecha de migración con @velnae 
- Crear workflow para la automatización de publicación de nuevas versiones

**Comment by OscarDevCPP** [comment]
Recursos utilizados:
- https://foojay.io/today/how-to-release-a-java-module-with-jreleaser-to-maven-central-with-github-actions -> inspiración para integrar jreleaser en el mecanismo de despliegue.
- https://maciejwalkowiak.com/blog/publish-java-library-maven-central/#_6-create-a-github-action -> inspiración para configurar el pom.xml con jreleaser.
